name: Lighthouse
on:
  workflow_call:
    secrets:
      SECRETS_JSON:
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Run_Lighthouse_Tests:
    runs-on: ubuntu-latest
    steps:
      # BEGIN INSTALLATION
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: pnpm install
      - name: Install bun
        run: npm install -g bun
      - name: Install Unlighthouse
        run: npm install -g @unlighthouse/cli puppeteer netlify-cli
      # END INSTALLATION
      
      - name: Build
        run: bun run gatsby build

      - name: Serve
        run: bun run gatsby serve & SERVER_PID=$!

      - name: Run Unlighthouse
        run: unlighthouse-ci --site http://localhost:9000/ --build-static --output-path ./audit-report

      - name: Deploy to Github
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone https://$GITHUB_ACTOR:${{ secrets.GH_PAT }}@github.com/reformcollective/unlighthouse-reports.git
          cd unlighthouse-reports
          touch netlify.toml
          echo "[build]" >> netlify.toml
          echo "  base = \"./${{ github.sha }}\"" >> netlify.toml
          mkdir ${{ github.sha }}
          cd ${{ github.sha }}
          cp -r ../../audit-report/* .
          cd ..
          git add .
          git commit -m "${{ github.repository }} - $(date +'%Y-%m-%d %H:%M:%S')"
          git push

      - name: Post comment
        uses: JoseThen/comment-pr@v1.2.0
        with:
          comment: 'Report Link: https://deft-mochi-caac3e.netlify.app/'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
